# Generated by Django 3.2.12 on 2023-04-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabindex', models.IntegerField(db_column='vocabIndex')),
                ('vocab', models.CharField(max_length=40)),
                ('pronounce', models.CharField(max_length=40)),
                ('meaning', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dictionary',
                'managed': False,
            },
        ),
    ]
